# This is a basic workflow to help you get started with Actions

name: Build Debug

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get install idn libidn11-dev
          sudo apt-get install libvlc-dev libvlccore-dev vlc
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install tjson
          haxelib install lime
          haxelib install openfl
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib --never git flixel-leather https://github.com/Leather128/flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib install hxcpp-debug-server
          haxelib install markdown
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux -debug --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linuxBuild
          path: 'export/debug/linux/bin' 
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install tjson
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install lime
          haxelib install openfl
          haxelib --never git flixel-leather https://github.com/Leather128/flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib install hxcpp-debug-server
          haxelib install markdown
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows -debug --app-version="4.0.0-${{ github.run_id}}" -dce no
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windowsBuild
          path: export/debug/windows/bin
  buildMac:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install tjson
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit
          haxelib install lime
          haxelib install openfl
          haxelib --never git flixel-leather https://github.com/Leather128/flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib install hxcpp-debug-server
          haxelib install markdown
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac -debug --app-version="4.0.0-${{ github.run_id}}" -dce no
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: macBuild
          path: export/debug/macos/bin
